name: Deploy to Test

on:
  push:
    branches:
      - develop
      - feat/96/deploy-workflow

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: test
      secret_prefix: "TEST_"
    secrets: inherit
